brew install stress
brew install xz
brew install tmux
brew install tree
brew install wget
brew install wrk
brew install redis
brew install iperf3
brew install pidof
brew install libressl
brew install readline
brew install zstd
brew install axel
brew install htop
brew install jemalloc
brew install jq
brew install bzip2
brew install p7zip
brew install mas
