install annie
install autoconf
install axel
install bison
install bzip2
install curl
install dshb
install htop
install icu4c
install iperf3
install jemalloc
install jpeg
install jq
install libedit
install libiconv
install libpng
install libressl
install libxml2
install libzip
install pidof
install python@3.8
install re2c
install redis
install rtorrent
install stress
install tidy-html5
install tmux
install tree
install unrar
install wget
install wrk
install youtube-dl
install zlib
